version: "3.8"
services:
  db:
    container_name: projet-genesis-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
    networks:
      - app-network

  app:
    container_name: projet-genesis-app
    image: ghcr.io/tayasaki/projet-genesis:latest
    ports:
      - 3000:3000
    command: sh -c "npx prisma db push --skip-generate && node server.js"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/projet-genesis
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=votresupersecret
      - AUTH_GITHUB_ID=votregithubid
      - AUTH_GITHUB_SECRET=votregithubsecret
      - AUTH_DISCORD_ID=votrediscordid
      - AUTH_DISCORD_SECRET=votrediscordsecret
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
